--
-- JBoss, Home of Professional Open Source
-- Copyright 2013, Red Hat, Inc. and/or its affiliates, and individual
-- contributors by the @authors tag. See the copyright.txt in the
-- distribution for a full listing of individual contributors.
--
-- Licensed under the Apache License, Version 2.0 (the 'License');
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
-- http://www.apache.org/licenses/LICENSE-2.0
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an 'AS IS' BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--

-- You can use this file to load seed data into the database using SQL statements
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (1,'AD','AND','T','020','T','Andorra','Andorra','Andorra')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (2,'AE','ARE','T','784','T','United Arab Emirates','United Arab Emirates','United Arab Emirates')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (3,'AF','AFG','T','004','T','Afghanistan','Afghanistan','Afghanistan')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (4,'AG','ATG','T','028','T','Antigua and Barbuda','Antigua and Barbuda','Antigua and Barbuda')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (5,'AI','AIA','T','660','T','Anguilla','Anguilla','Anguilla')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (6,'AL','ALB','T','008','T','Albania','Albania','Albania')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (7,'AM','ARM','T','051','T','Armenia','Armenia','Armenia')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (8,'AO','AGO','T','024','T','Angola','Angola','Angola')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (9,'AQ','ATA','T','010','T','Antarctica','Antarctica','Antarctica')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (10,'AR','ARG','T','032','T','Argentina','Argentina','Argentina')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (11,'AS','ASM','T','016','T','American Samoa','American Samoa','American Samoa')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (12,'AT','AUT','T','040','T','Austria','Austria','Austria')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (13,'AU','AUS','T','036','T','Australia','Australia','Australia')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (14,'AW','ABW','T','533','T','Aruba','Aruba','Aruba')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (15,'AX','ALA','T','248','T','�land','�land','�land')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (16,'AZ','AZE','T','031','T','Azerbaijan','Azerbaijan','Azerbaijan')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (17,'BA','BIH','T','070','T','Bosnia and Herzegovina','Bosnia and Herzegovina','Bosnia and Herzegovina')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (18,'BB','BRB','T','052','T','Barbados','Barbados','Barbados')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (19,'BD','BGD','T','050','T','Bangladesh','Bangladesh','Bangladesh')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (20,'BE','BEL','T','056','T','Belgium','Belgium','Belgium')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (21,'BF','BFA','T','854','T','Burkina Faso','Burkina Faso','Burkina Faso')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (22,'BG','BGR','T','100','T','Bulgaria','Bulgaria','Bulgaria')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (23,'BH','BHR','T','048','T','Bahrain','Bahrain','Bahrain')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (24,'BI','BDI','T','108','T','Burundi','Burundi','Burundi')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (25,'BJ','BEN','T','204','T','Benin','Benin','Benin')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (26,'BL','BLM','T','652','T','Saint Barth�lemy','Saint Barth�lemy','Saint Barth�lemy')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (27,'BM','BMU','T','060','T','Bermuda','Bermuda','Bermuda')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (28,'BN','BRN','T','096','T','Brunei','Brunei','Brunei')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (29,'BO','BOL','T','068','T','Bolivia','Bolivia','Bolivia')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (30,'BQ','BES','T','535','T','Bonaire','Bonaire','Bonaire')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (31,'BR','BRA','T','076','T','Brazil','Brazil','Brazil')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (32,'BS','BHS','T','044','T','Bahamas','Bahamas','Bahamas')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (33,'BT','BTN','T','064','T','Bhutan','Bhutan','Bhutan')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (34,'BV','BVT','T','074','T','Bouvet Island','Bouvet Island','Bouvet Island')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (35,'BW','BWA','T','072','T','Botswana','Botswana','Botswana')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (36,'BY','BLR','T','112','T','Belarus','Belarus','Belarus')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (37,'BZ','BLZ','T','084','T','Belize','Belize','Belize')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (38,'CA','CAN','T','124','T','Canada','Canada','Canada')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (39,'CC','CCK','T','166','T','Cocos [Keeling] Islands','Cocos [Keeling] Islands','Cocos [Keeling] Islands')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (40,'CD','COD','T','180','T','Democratic Republic of the Congo','Democratic Republic of the Congo','Democratic Republic of the Congo')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (41,'CF','CAF','T','140','T','Central African Republic','Central African Republic','Central African Republic')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (42,'CG','COG','T','178','T','Republic of the Congo','Republic of the Congo','Republic of the Congo')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (43,'CH','CHE','T','756','T','Switzerland','Switzerland','Switzerland')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (44,'CI','CIV','T','384','T','Ivory Coast','Ivory Coast','Ivory Coast')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (45,'CK','COK','T','184','T','Cook Islands','Cook Islands','Cook Islands')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (46,'CL','CHL','T','152','T','Chile','Chile','Chile')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (47,'CM','CMR','T','120','T','Cameroon','Cameroon','Cameroon')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (48,'CN','CHN','T','156','T','China','China','China')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (49,'CO','COL','T','170','T','Colombia','Colombia','Colombia')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (50,'CR','CRI','T','188','T','Costa Rica','Costa Rica','Costa Rica')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (51,'CU','CUB','T','192','T','Cuba','Cuba','Cuba')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (52,'CV','CPV','T','132','T','Cape Verde','Cape Verde','Cape Verde')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (53,'CW','CUW','T','531','T','Curacao','Curacao','Curacao')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (54,'CX','CXR','T','162','T','Christmas Island','Christmas Island','Christmas Island')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (55,'CY','CYP','T','196','T','Cyprus','Cyprus','Cyprus')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (56,'CZ','CZE','T','203','T','Czech Republic','Czech Republic','Czech Republic')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (57,'DE','DEU','T','276','T','Germany','Germany','Germany')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (58,'DJ','DJI','T','262','T','Djibouti','Djibouti','Djibouti')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (59,'DK','DNK','T','208','T','Denmark','Denmark','Denmark')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (60,'DM','DMA','T','212','T','Dominica','Dominica','Dominica')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (61,'DO','DOM','T','214','T','Dominican Republic','Dominican Republic','Dominican Republic')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (62,'DZ','DZA','T','012','T','Algeria','Algeria','Algeria')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (63,'EC','ECU','T','218','T','Ecuador','Ecuador','Ecuador')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (64,'EE','EST','T','233','T','Estonia','Estonia','Estonia')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (65,'EG','EGY','T','818','T','Egypt','Egypt','Egypt')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (66,'EH','ESH','T','732','T','Western Sahara','Western Sahara','Western Sahara')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (67,'ER','ERI','T','232','T','Eritrea','Eritrea','Eritrea')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (68,'ES','ESP','T','724','T','Spain','Spain','Spain')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (69,'ET','ETH','T','231','T','Ethiopia','Ethiopia','Ethiopia')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (70,'FI','FIN','T','246','T','Finland','Finland','Finland')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (71,'FJ','FJI','T','242','T','Fiji','Fiji','Fiji')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (72,'FK','FLK','T','238','T','Falkland Islands','Falkland Islands','Falkland Islands')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (73,'FM','FSM','T','583','T','Micronesia','Micronesia','Micronesia')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (74,'FO','FRO','T','234','T','Faroe Islands','Faroe Islands','Faroe Islands')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (75,'FR','FRA','T','250','T','France','France','France')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (76,'GA','GAB','T','266','T','Gabon','Gabon','Gabon')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (77,'GB','GBR','T','826','T','United Kingdom','United Kingdom','United Kingdom')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (78,'GD','GRD','T','308','T','Grenada','Grenada','Grenada')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (79,'GE','GEO','T','268','T','Georgia','Georgia','Georgia')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (80,'GF','GUF','T','254','T','French Guiana','French Guiana','French Guiana')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (81,'GG','GGY','T','831','T','Guernsey','Guernsey','Guernsey')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (82,'GH','GHA','T','288','T','Ghana','Ghana','Ghana')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (83,'GI','GIB','T','292','T','Gibraltar','Gibraltar','Gibraltar')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (84,'GL','GRL','T','304','T','Greenland','Greenland','Greenland')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (85,'GM','GMB','T','270','T','Gambia','Gambia','Gambia')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (86,'GN','GIN','T','324','T','Guinea','Guinea','Guinea')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (87,'GP','GLP','T','312','T','Guadeloupe','Guadeloupe','Guadeloupe')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (88,'GQ','GNQ','T','226','T','Equatorial Guinea','Equatorial Guinea','Equatorial Guinea')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (89,'GR','GRC','T','300','T','Greece','Greece','Greece')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (90,'GS','SGS','T','239','T','South Georgia and the South Sandwich Islands','South Georgia and the South Sandwich Islands','South Georgia and the South Sandwich Islands')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (91,'GT','GTM','T','320','T','Guatemala','Guatemala','Guatemala')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (92,'GU','GUM','T','316','T','Guam','Guam','Guam')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (93,'GW','GNB','T','624','T','Guinea-Bissau','Guinea-Bissau','Guinea-Bissau')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (94,'GY','GUY','T','328','T','Guyana','Guyana','Guyana')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (95,'HK','HKG','T','344','T','Hong Kong','Hong Kong','Hong Kong')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (96,'HM','HMD','T','334','T','Heard Island and McDonald Islands','Heard Island and McDonald Islands','Heard Island and McDonald Islands')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (97,'HN','HND','T','340','T','Honduras','Honduras','Honduras')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (98,'HR','HRV','T','191','T','Croatia','Croatia','Croatia')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (99,'HT','HTI','T','332','T','Haiti','Haiti','Haiti')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (100,'HU','HUN','T','348','T','Hungary','Hungary','Hungary')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (101,'ID','IDN','T','360','T','Indonesia','Indonesia','Indonesia')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (102,'IE','IRL','T','372','T','Ireland','Ireland','Ireland')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (103,'IL','ISR','T','376','T','Israel','Israel','Israel')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (104,'IM','IMN','T','833','T','Isle of Man','Isle of Man','Isle of Man')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (105,'IN','IND','T','356','T','India','India','India')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (106,'IO','IOT','T','086','T','British Indian Ocean Territory','British Indian Ocean Territory','British Indian Ocean Territory')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (107,'IQ','IRQ','T','368','T','Iraq','Iraq','Iraq')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (108,'IR','IRN','T','364','T','Iran','Iran','Iran')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (109,'IS','ISL','T','352','T','Iceland','Iceland','Iceland')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (110,'IT','ITA','T','380','T','Italy','Italy','Italy')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (111,'JE','JEY','T','832','T','Jersey','Jersey','Jersey')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (112,'JM','JAM','T','388','T','Jamaica','Jamaica','Jamaica')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (113,'JO','JOR','T','400','T','Jordan','Jordan','Jordan')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (114,'JP','JPN','T','392','T','Japan','Japan','Japan')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (115,'KE','KEN','T','404','T','Kenya','Kenya','Kenya')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (116,'KG','KGZ','T','417','T','Kyrgyzstan','Kyrgyzstan','Kyrgyzstan')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (117,'KH','KHM','T','116','T','Cambodia','Cambodia','Cambodia')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (118,'KI','KIR','T','296','T','Kiribati','Kiribati','Kiribati')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (119,'KM','COM','T','174','T','Comoros','Comoros','Comoros')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (120,'KN','KNA','T','659','T','Saint Kitts and Nevis','Saint Kitts and Nevis','Saint Kitts and Nevis')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (121,'KP','PRK','T','408','T','North Korea','North Korea','North Korea')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (122,'KR','KOR','T','410','T','South Korea','South Korea','South Korea')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (123,'KW','KWT','T','414','T','Kuwait','Kuwait','Kuwait')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (124,'KY','CYM','T','136','T','Cayman Islands','Cayman Islands','Cayman Islands')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (125,'KZ','KAZ','T','398','T','Kazakhstan','Kazakhstan','Kazakhstan')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (126,'LA','LAO','T','418','T','Laos','Laos','Laos')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (127,'LB','LBN','T','422','T','Lebanon','Lebanon','Lebanon')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (128,'LC','LCA','T','662','T','Saint Lucia','Saint Lucia','Saint Lucia')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (129,'LI','LIE','T','438','T','Liechtenstein','Liechtenstein','Liechtenstein')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (130,'LK','LKA','T','144','T','Sri Lanka','Sri Lanka','Sri Lanka')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (131,'LR','LBR','T','430','T','Liberia','Liberia','Liberia')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (132,'LS','LSO','T','426','T','Lesotho','Lesotho','Lesotho')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (133,'LT','LTU','T','440','T','Lithuania','Lithuania','Lithuania')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (134,'LU','LUX','T','442','T','Luxembourg','Luxembourg','Luxembourg')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (135,'LV','LVA','T','428','T','Latvia','Latvia','Latvia')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (136,'LY','LBY','T','434','T','Libya','Libya','Libya')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (137,'MA','MAR','T','504','T','Morocco','Morocco','Morocco')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (138,'MC','MCO','T','492','T','Monaco','Monaco','Monaco')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (139,'MD','MDA','T','498','T','Moldova','Moldova','Moldova')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (140,'ME','MNE','T','499','T','Montenegro','Montenegro','Montenegro')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (141,'MF','MAF','T','663','T','Saint Martin','Saint Martin','Saint Martin')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (142,'MG','MDG','T','450','T','Madagascar','Madagascar','Madagascar')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (143,'MH','MHL','T','584','T','Marshall Islands','Marshall Islands','Marshall Islands')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (144,'MK','MKD','T','807','T','Macedonia','Macedonia','Macedonia')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (145,'ML','MLI','T','466','T','Mali','Mali','Mali')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (146,'MM','MMR','T','104','T','Myanmar [Burma]','Myanmar [Burma]','Myanmar [Burma]')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (147,'MN','MNG','T','496','T','Mongolia','Mongolia','Mongolia')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (148,'MO','MAC','T','446','T','Macao','Macao','Macao')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (149,'MP','MNP','T','580','T','Northern Mariana Islands','Northern Mariana Islands','Northern Mariana Islands')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (150,'MQ','MTQ','T','474','T','Martinique','Martinique','Martinique')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (151,'MR','MRT','T','478','T','Mauritania','Mauritania','Mauritania')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (152,'MS','MSR','T','500','T','Montserrat','Montserrat','Montserrat')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (153,'MT','MLT','T','470','T','Malta','Malta','Malta')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (154,'MU','MUS','T','480','T','Mauritius','Mauritius','Mauritius')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (155,'MV','MDV','T','462','T','Maldives','Maldives','Maldives')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (156,'MW','MWI','T','454','T','Malawi','Malawi','Malawi')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (157,'MX','MEX','T','484','T','Mexico','Mexico','Mexico')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (158,'MY','MYS','T','458','T','Malaysia','Malaysia','Malaysia')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (159,'MZ','MOZ','T','508','T','Mozambique','Mozambique','Mozambique')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (160,'NA','NAM','T','516','T','Namibia','Namibia','Namibia')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (161,'NC','NCL','T','540','T','New Caledonia','New Caledonia','New Caledonia')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (162,'NE','NER','T','562','T','Niger','Niger','Niger')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (242,'VU','VUT','T','548','T','Vanuatu','Vanuatu','Vanuatu')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (163,'NF','NFK','T','574','T','Norfolk Island','Norfolk Island','Norfolk Island')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (164,'NG','NGA','T','566','T','Nigeria','Nigeria','Nigeria')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (165,'NI','NIC','T','558','T','Nicaragua','Nicaragua','Nicaragua')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (166,'NL','NLD','T','528','T','Netherlands','Netherlands','Netherlands')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (167,'NO','NOR','T','578','T','Norway','Norway','Norway')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (168,'NP','NPL','T','524','T','Nepal','Nepal','Nepal')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (169,'NR','NRU','T','520','T','Nauru','Nauru','Nauru')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (170,'NU','NIU','T','570','T','Niue','Niue','Niue')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (171,'NZ','NZL','T','554','T','New Zealand','New Zealand','New Zealand')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (172,'OM','OMN','T','512','T','Oman','Oman','Oman')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (173,'PA','PAN','T','591','T','Panama','Panama','Panama')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (174,'PE','PER','T','604','T','Peru','Peru','Peru')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (175,'PF','PYF','T','258','T','French Polynesia','French Polynesia','French Polynesia')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (176,'PG','PNG','T','598','T','Papua New Guinea','Papua New Guinea','Papua New Guinea')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (177,'PH','PHL','T','608','T','Philippines','Philippines','Philippines')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (178,'PK','PAK','T','586','T','Pakistan','Pakistan','Pakistan')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (179,'PL','POL','T','616','T','Poland','Poland','Poland')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (180,'PM','SPM','T','666','T','Saint Pierre and Miquelon','Saint Pierre and Miquelon','Saint Pierre and Miquelon')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (181,'PN','PCN','T','612','T','Pitcairn Islands','Pitcairn Islands','Pitcairn Islands')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (182,'PR','PRI','T','630','T','Puerto Rico','Puerto Rico','Puerto Rico')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (183,'PS','PSE','T','275','T','Palestine','Palestine','Palestine')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (184,'PT','PRT','T','620','T','Portugal','Portugal','Portugal')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (185,'PW','PLW','T','585','T','Palau','Palau','Palau')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (186,'PY','PRY','T','600','T','Paraguay','Paraguay','Paraguay')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (187,'QA','QAT','T','634','T','Qatar','Qatar','Qatar')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (188,'RE','REU','T','638','T','R�union','R�union','R�union')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (189,'RO','ROU','T','642','T','Romania','Romania','Romania')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (190,'RS','SRB','T','688','T','Serbia','Serbia','Serbia')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (191,'RU','RUS','T','643','T','Russia','Russia','Russia')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (192,'RW','RWA','T','646','T','Rwanda','Rwanda','Rwanda')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (193,'SA','SAU','T','682','T','Saudi Arabia','Saudi Arabia','Saudi Arabia')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (194,'SB','SLB','T','090','T','Solomon Islands','Solomon Islands','Solomon Islands')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (195,'SC','SYC','T','690','T','Seychelles','Seychelles','Seychelles')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (196,'SD','SDN','T','729','T','Sudan','Sudan','Sudan')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (197,'SE','SWE','T','752','T','Sweden','Sweden','Sweden')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (198,'SG','SGP','T','702','T','Singapore','Singapore','Singapore')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (199,'SH','SHN','T','654','T','Saint Helena','Saint Helena','Saint Helena')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (200,'SI','SVN','T','705','T','Slovenia','Slovenia','Slovenia')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (201,'SJ','SJM','T','744','T','Svalbard and Jan Mayen','Svalbard and Jan Mayen','Svalbard and Jan Mayen')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (202,'SK','SVK','T','703','T','Slovakia','Slovakia','Slovakia')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (203,'SL','SLE','T','694','T','Sierra Leone','Sierra Leone','Sierra Leone')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (204,'SM','SMR','T','674','T','San Marino','San Marino','San Marino')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (205,'SN','SEN','T','686','T','Senegal','Senegal','Senegal')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (206,'SO','SOM','T','706','T','Somalia','Somalia','Somalia')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (207,'SR','SUR','T','740','T','Suriname','Suriname','Suriname')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (208,'SS','SSD','T','728','T','South Sudan','South Sudan','South Sudan')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (209,'ST','STP','T','678','T','S�o Tom� and Pr�ncipe','S�o Tom� and Pr�ncipe','S�o Tom� and Pr�ncipe')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (210,'SV','SLV','T','222','T','El Salvador','El Salvador','El Salvador')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (211,'SX','SXM','T','534','T','Sint Maarten','Sint Maarten','Sint Maarten')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (212,'SY','SYR','T','760','T','Syria','Syria','Syria')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (213,'SZ','SWZ','T','748','T','Swaziland','Swaziland','Swaziland')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (214,'TC','TCA','T','796','T','Turks and Caicos Islands','Turks and Caicos Islands','Turks and Caicos Islands')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (215,'TD','TCD','T','148','T','Chad','Chad','Chad')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (216,'TF','ATF','T','260','T','French Southern Territories','French Southern Territories','French Southern Territories')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (217,'TG','TGO','T','768','T','Togo','Togo','Togo')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (218,'TH','THA','T','764','T','Thailand','Thailand','Thailand')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (219,'TJ','TJK','T','762','T','Tajikistan','Tajikistan','Tajikistan')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (220,'TK','TKL','T','772','T','Tokelau','Tokelau','Tokelau')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (221,'TL','TLS','T','626','T','East Timor','East Timor','East Timor')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (222,'TM','TKM','T','795','T','Turkmenistan','Turkmenistan','Turkmenistan')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (223,'TN','TUN','T','788','T','Tunisia','Tunisia','Tunisia')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (224,'TO','TON','T','776','T','Tonga','Tonga','Tonga')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (225,'TR','TUR','T','792','T','Turkey','Turkey','Turkey')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (226,'TT','TTO','T','780','T','Trinidad and Tobago','Trinidad and Tobago','Trinidad and Tobago')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (227,'TV','TUV','T','798','T','Tuvalu','Tuvalu','Tuvalu')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (228,'TW','TWN','T','158','T','Taiwan','Taiwan','Taiwan')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (229,'TZ','TZA','T','834','T','Tanzania','Tanzania','Tanzania')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (230,'UA','UKR','T','804','T','Ukraine','Ukraine','Ukraine')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (231,'UG','UGA','T','800','T','Uganda','Uganda','Uganda')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (232,'UM','UMI','T','581','T','U.S. Minor Outlying Islands','U.S. Minor Outlying Islands','U.S. Minor Outlying Islands')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (233,'US','USA','T','840','T','United States','United States','United States')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (234,'UY','URY','T','858','T','Uruguay','Uruguay','Uruguay')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (235,'UZ','UZB','T','860','T','Uzbekistan','Uzbekistan','Uzbekistan')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (236,'VA','VAT','T','336','T','Vatican City','Vatican City','Vatican City')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (237,'VC','VCT','T','670','T','Saint Vincent and the Grenadines','Saint Vincent and the Grenadines','Saint Vincent and the Grenadines')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (238,'VE','VEN','T','862','T','Venezuela','Venezuela','Venezuela')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (239,'VG','VGB','T','092','T','British Virgin Islands','British Virgin Islands','British Virgin Islands')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (240,'VI','VIR','T','850','T','U.S. Virgin Islands','U.S. Virgin Islands','U.S. Virgin Islands')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (241,'VN','VNM','T','704','T','Vietnam','Vietnam','Vietnam')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (243,'WF','WLF','T','876','T','Wallis and Futuna','Wallis and Futuna','Wallis and Futuna')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (244,'WS','WSM','T','882','T','Samoa','Samoa','Samoa')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (245,'XK','XKX','T','0','T','Kosovo','Kosovo','Kosovo')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (246,'YE','YEM','T','887','T','Yemen','Yemen','Yemen')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (247,'YT','MYT','T','175','T','Mayotte','Mayotte','Mayotte')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (248,'ZA','ZAF','T','710','T','South Africa','South Africa','South Africa')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (249,'ZM','ZMB','T','894','T','Zambia','Zambia','Zambia')
insert into COUNTRY_CODE (id, alpha2Code, alpha3Code, independent, numericCode, status, shortNameEn, shortNameUppercaseEn, fullNameEn) values (250,'ZW','ZWE','T','716','T','Zimbabwe','Zimbabwe','Zimbabwe')
